### ISSUE TITLE
[Feature] Session MMR Tracking

### ISSUE THREAD

**Issue by GrantJL** [GrantJL/rl-lobby-ranks#10]
Add an optional Session MMR Tracking
- [ ] Tracks current playlist (shows current playlist, tracks multiple throughout session)
- [ ] Tracking Display options (toggle and orderable)
    - [ ] Current Playlist and MMR
    - [ ] # Game
    - [ ] # Wins, Losses, Win/Loss, Win/Games, Win %
    - [ ] # Win/Loss Streak
    - [ ] # MRR Change Last Match / Session
    - [ ] More...?
    - [ ] Current User Time?
- [ ] Optionally Attach Stats to bottom of scoreboard (or own custom position, anchors)
